### PR TITLE
set default tab length to 4 spaces

### LINKED ISSUE #76: default tab should be 4 spaces?
The Julia style guide prefers 4 spaces, but currently the default tab spacing in atom is 2 spaces.

### PR DESCRIPTION
**Pull request by pfitzseb**
fixes #76

### CODE REVIEW

**Comment by spencerlyon2** [comment]
This was originally part of the package, but @MikeInnes suggested we leave it out. 

@MikeInnes what do you think about this?

**Comment by pfitzseb** [comment]
I think the concern was that this overrides Atom's default tab length (see https://github.com/JuliaEditorSupport/atom-language-julia/commit/6ee2e499ed319bd11a80f1e3f020ebf0c0d056d3). It doesn't though, I still have `Default: 2` in Settings > Editor > Tab Length.

**Comment by MikeInnes** [comment]
When we did this in LT a while back, we had confusion from people because the default setting didn't line up with what they were getting in the editor – language-specific settings don't seem to be a well-known feature. For that reason I think it's best to let people override language defaults explicitly.

That would be kind of a hassle if not for indent-detective, which is a very general solution to this problem. So perhaps bundling that with Juno and documenting the option for those who want it is a good compromise between those issues.

**Comment by pfitzseb** [comment]
I'm gonna close this since `indent-detective` should correctly identify indentation in pretty much all cases now.

**Comment by StefanKarpinski** [comment]
The default indent for Julia code should be 4 spaces.

**Comment by sglyon** [comment]
Easy enough. I'll make the change soon unless someone beats me to it

**Pull request merged**
