### PR TITLE
=> is no function definition

### LINKED ISSUE #84: Pair infix constructors confuse coloring
Any function calls that occur on the same line as a `=>` gets colored as a function definition. This actually extends outward to the left; nested calls are all colored, unless an outer call occurs on a separate line.

screen shot 2016-10-01 at 1 44 09 pm

Also note the weird indentation--though I think that's https://github.com/JunoLab/Atom.jl/issues/62, which has been addressed.

### PR DESCRIPTION
**Pull request by pfitzseb**
fixes #84.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Can you please add s spec for this one?

**Comment by spencerlyon2** [comment]
Awesome, thanks for the test. 

Does the spec cover the original issue from #84?

**Comment by pfitzseb** [comment]
Yes, it does -- `Dict` (and all other function calls) where erroneously tokenized as `entity.name.function.julia`.
Can't run specs locally right now for some reason, but the latest commit should be working.

**Comment by pfitzseb** [comment]
Well, that took a bit... Should be all good now though.

**Comment by spencerlyon2** [comment]
Great, thanks!

**Comment by spencerlyon2** [comment]
I just pushed a new release to apm for all these PRs

**Comment by pfitzseb** [comment]
Great, thanks!

**Pull request merged**
