### PR TITLE
move `.<=` ahead of `.<`

### PR DESCRIPTION
**Pull request by jianghaizhu**
Right now, `.<=` is recognized as `.<` then `=`. Moving `.<=` ahead of `.<`solves this problem.

### CODE REVIEW

**Comment by sglyon** [comment]
Thanks for the fix, will you please add a test?

**Comment by jianghaizhu** [comment]
Where are other tests located?

**Comment by pfitzseb** [comment]
[Here](https://github.com/JuliaEditorSupport/atom-language-julia/blob/master/spec/julia-spec.coffee).

**Comment by jianghaizhu** [comment]
I don't know anything about coffee script. But here is my attempt.

**Comment by sglyon** [comment]
Thanks, you did great with the test!

**Comment by jianghaizhu** [comment]
Thanks! I made more changes in my fork to add `>:`. It looks like you merged that as well. Is that ok? I probably should have created a new branch for that.

**Comment by sglyon** [comment]
That was totally fine. The change was so similar to the original one so I was happy to merge them together

**Comment by jianghaizhu** [comment]
Great!

**Pull request merged**
