### PR TITLE
Include language-R syntax highlighting for docsting macro

### PR DESCRIPTION
**Pull request by pmarg**

### CODE REVIEW

**Comment by pfitzseb** [comment]
What package provides the R syntax highlighting? It doesn't seem to be included in the default Atom distribution. Would be good to mention that in the readme, I think.

**Comment by pmarg** [comment]
No, R syntax is not part of the default distribution. There are some packages such as
[atom-language-r](https://atom.io/packages/atom-language-r),  [language-r](https://atom.io/packages/language-r) [unmaintained] and [r-syntax](https://atom.io/packages/r-syntax).

**Comment by pfitzseb** [comment]
Can you add a note to the readme that points out (one of) those packages?

**Comment by pfitzseb** [comment]
Awesome, thanks!

**Pull request merged**
