### PR TITLE
add more constants

### PR DESCRIPTION
**Pull request by aviatesk**
adapted from:
- https://github.com/JuliaLang/julia/blob/f39cb43032e8a6e10cd3c8cd4d806676ff705c0c/base/exports.jl#L147-L158
- https://github.com/JuliaLang/julia/blob/f39cb43032e8a6e10cd3c8cd4d806676ff705c0c/base/exports.jl#L133-L145

### CODE REVIEW

**Comment by pfitzseb** [comment]
I'm slightly hesitant to add these because they aren't available in `baremodule`s. Might not be a big problem though.

**Comment by aviatesk** [comment]
fair point. 

well, the same thing actually applies most of the existing "constants" ?
```julia
baremodule Foo

using Base: Base

# existing numeric
Base.@show Base.@isdefined(im)
Base.@show Base.@isdefined(Inf)

# existing "language" core
Base.@show Base.@isdefined(missing)
Base.@show Base.@isdefined(nothing)

# new
Base.@show Base.@isdefined(π)
Base.@show Base.@isdefined(stdout)

end
```
All of them are not defined in `baremodule Foo`

So in this sense what's really constant are only `false/true`.

---

My initial motivation for this was that I thought it _might_ be a bit useful for detecting typos around e.g. `stdout`. fwiw, I found GitLab also highlights them:
Screen Shot 2020-10-21 at 17 53 55

**Comment by pfitzseb** [comment]
You could argue that a linter should take care of that :)

But fair enough, let's add these. Seems fairly unlikely that people are going to shadow these variables or whatever.

**Comment by aviatesk** [comment]
> You could argue that a linter should take care of that :)

haha, yeah definitely.
anyway, thanks always for accepting my idea !

**Pull request merged**
