### PR TITLE
fix ternary op tokenization

### PR DESCRIPTION
**Pull request by pfitzseb**
Fixes https://github.com/JuliaEditorSupport/atom-language-julia/issues/217.

This isn't correct in all cases because it will tokenize every instance of `\s:\s` as part of a ternary, no matter if it's preceded by a `?`. Shouldn't matter too much in practice, but I can also just disable the `\s:\s` part of this such that only `\s?\s` is marked as part of a ternary.

### CODE REVIEW

**Review by aviatesk — APPROVED** [review]
> This isn't correct in all cases because it will tokenize every instance of \s:\s as part of a ternary, no matter if it's preceded by a ?

yeah I think this is okay for now. ~~not sure if there is any theme that wants to use different colors for the unit range syntax and the ternary expression.~~ nvm, I don't know if there is standard syntax that only uses `\\s:\\s`

**Comment by CameronBieganek** [comment]
> nvm, I don't know if there is standard syntax that only uses `\\s:\\s`

Well, ranges can have spaces around the colon, like `1 : 3`. In fact, that syntax was not tokenized at all prior to this PR:

Screen Shot 2020-10-24 at 5 47 14 PM

So, the fact that it is now tokenized by this PR is nice. I mean, conceptually that should still be a `keyword.operator.range.julia` token, since the range token type already exists, but in my color theme I will probably color the ternary operator the same as the other operators, so the difference won't actually be visible.

By the way, should I open an issue in the VS Code repo to track incorporating the recent changes to the grammar into the julia-vscode repo, or is that already on the radar?

**Comment by pfitzseb** [comment]
> So, the fact that it is now tokenized by this PR is nice. I mean, conceptually that should still be a `keyword.operator.range.julia` token, since the range token type already exists, but in my color theme I will probably color the ternary operator the same as the other operators, so the difference won't actually be visible.

Do you think it'd be more useful to tokenize it as `keyword.operator.colon.julia` then?

> By the way, should I open an issue in the VS Code repo to track incorporating the recent changes to the grammar into the julia-vscode repo, or is that already on the radar?

Nah, I'll take care of that.

**Comment by aviatesk** [comment]
and let's make a new release for this package itself for now ?

**Comment by CameronBieganek** [comment]
> Do you think it'd be more useful to tokenize it as `keyword.operator.colon.julia` then?

Do you mean tokenize all (single) colons as `keyword.operator.colon.julia` and all question marks as `keyword.operator.ternary.julia` ? In other words, a ternary operator would tokenize into a `keyword.operator.ternary.julia` token followed by <something> followed by a `keyword.operator.colon.julia` token?

Some TextMate grammars like the Python and the Javascript grammars allow for deeply nested scopes, but I don't think that colorizing differently based on nested scopes usually makes sense for a color theme. It's usually better just to be consistent for different types of symbols. So, having tokens for different characters is not a bad way to go. In other words, it wouldn't be bad to have `punctuation.questionmark` and `punctuation.colon` or something like that.

For that matter, you could also split `meta.bracket` into separate tokens like

- `punctuation.parenthesis`
- `punctuation.comma`
- `punctuation.semicolon`
- `punctuation.bracket`
- `punctuation.curlybraces`

But I wouldn't consider that to be a particularly high priority. Even if that change was made, I'm not sure that I would move away from my current uniform coloring of `meta.bracket` as orange.

**Pull request merged**
